const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const root=__dirname;
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
const game=read('game.js');
const system=read('ui-system.css');
const layout=read('style.css');
const rules=read('UI_SYSTEM.md');
const html=read('index.html');

for(const archetype of ['.ui-page','.ui-workspace','.ui-canvas-workspace','.ui-dialog']){
  assert.match(rules,new RegExp(archetype.replace('.',String.raw`\.`)),`设计规范必须登记页面母版 ${archetype}`);
}
for(const primitive of ['.ui-workspace__shell','.ui-workspace__main','.ui-workspace__footer','.ui-workspace__exit','.ui-module-header','.ui-segmented','.ui-art-frame','.ui-stat-grid']){
  assert.match(system,new RegExp(primitive.replace('.',String.raw`\.`)),`统一样式文件必须实现 ${primitive}`);
}
for(const token of ['--ui-metal','--ui-metal-warm','--ui-oxide'])assert.match(system,new RegExp(token),`统一样式必须提供材质令牌 ${token}`);
assert.match(system,/Mobile interaction contract[\s\S]*touch-action:manipulation[\s\S]*#panel button:not\(\.ui-icon-button\)[\s\S]*min-height:44px/,'统一样式必须让全部移动端普通按钮达到 44px');
assert.match(system,/\.ui-icon-button,[\s\S]*#panel \.map-tool,[\s\S]*width:44px!important;[\s\S]*height:44px!important;/,'成组图标按钮必须使用不重叠的 44px 实体点击区');
assert.match(game,/style\.setProperty\('--map-scale',view\.scale\)/,'地图视口必须把实时缩放倍率传给触摸层');
assert.match(system,/#panel \.mapnode::before[\s\S]*44px \/ var\(--map-scale,1\)/,'地图节点必须按缩放倍率反向补偿触摸区');
assert.match(game,/const pointerPair=[\s\S]*beginPinch=[\s\S]*Math\.hypot[\s\S]*pointercancel/,'地图必须支持以双指中点为锚点的触摸缩放');
for(const control of ['station-detail-workbench \\.station-step','battle-primary-controls \\.battle-action'])assert.match(system,new RegExp(control),`${control} 必须接入统一移动触摸规格`);
assert.match(system,/#panel\[data-view="settings"\]\.settings-home[\s\S]*overflow-y:auto!important[\s\S]*settings-storage-actions \.cloud-action[\s\S]*min-height:44px!important/,'紧凑设置首页不得以缩小按钮换取伪一屏');
assert.match(system,/#panel\.settings-home \.settings-media[\s\S]*overflow:visible[\s\S]*repeat\(3,minmax\(44px,auto\)\)/,'矮屏设置项变大后不得被旧容器裁切');
assert.match(system,/body\[data-ui="abyss-frame"\] #panel \.field-head-tool,[\s\S]*field-map-marker,[\s\S]*field-map-drawer-close[\s\S]*min-height:44px!important/,'后加载的野外场景样式不得缩小统一触摸区');
assert.match(system,/recipe-station-top,[\s\S]*station-detail-body,[\s\S]*npc-content-scroll,[\s\S]*battle-tool-rail \{ overscroll-behavior:contain; \}/,'独立滚动区必须阻止滚动串联');
assert.match(system,/Adaptive HUD and long-copy resilience[\s\S]*grid-template-areas:[\s\S]*"meta settings"[\s\S]*"health energy"[\s\S]*\.hud-wing \{[\s\S]*display:contents/,'顶部工具与两条状态必须使用互不侵占的两层网格');
assert.match(system,/#metabar \.hud-meta \{[\s\S]*display:flex[\s\S]*align-items:center[\s\S]*#metabar #time,[\s\S]*#metabar #pt-label \{ font-size:11px[\s\S]*#metabar #pt-label::before/,'时间与轮回必须同字号对齐，并由非文字标记分隔');
assert.match(system,/#metabar \.g-val\.is-long \{[\s\S]*grid-template-columns:minmax\(0,1fr\)[\s\S]*#metabar \.g-val\.is-long \.g-limit::before/,'超长状态必须自动拆为当前值和上限两行，不得继续缩窄相邻区域');
assert.match(game,/function renderGaugeValue\([\s\S]*classList\.toggle\('is-long',[\s\S]*renderGaugeValue\('hp'[\s\S]*renderGaugeValue\('stamina'/,'顶部生命与能量必须共用自动长数值布局');
assert.match(system,/\.site-sheet\.item-detail-sheet,[\s\S]*\.skill-detail-panel,[\s\S]*\.tdet \{[\s\S]*overflow-y:auto/,'物品、技能与树节点详情必须在自身背景内滚动');
assert.match(system,/\.item-detail-note p,[\s\S]*\.skill-detail-main p,[\s\S]*\.tdet-story,[\s\S]*overflow-wrap:anywhere/,'详情正文必须允许长中文、英文和连续编号在背景框内断行');
assert.match(rules,/时间与轮回在第一层同一行[\s\S]*至少支持六位数值[\s\S]*不能依赖绝对定位或数值缩写[\s\S]*详情面板、上下文弹层和分屏详情[\s\S]*overflow:hidden/,'统一规范必须固定长状态值与详情正文的抗溢出规则');
assert.doesNotMatch(layout,/\.ui-workspace__|\.ui-module-header|\.ui-segmented|\.ui-art-frame|\.ui-stat-(?:grid|chip)/,'共享组件皮肤只能定义在 ui-system.css');
assert.match(layout,/New visual tokens, component skins and state variants belong in ui-system\.css/,'页面布局文件必须明确指向唯一视觉样式入口');
assert.match(game,/workspace-fullpage',immersiveWorkspace\|\|canvasWorkspace/,'沉浸工作区与画布必须统一切换全屏状态');
assert.match(game,/box\.classList\.toggle\('ui-page',rootPage\)/,'页面必须在渲染时挂载统一母版类');
assert.match(game,/state\.campView==='construct'\|\|state\.npcTarget/,'建筑管理整页不得残留地图悬浮按钮');
assert.ok((game.match(/workspaceExit\('/g)||[]).length>=4,'设施、建筑、商店与 NPC 必须复用统一底部退出构造器');
for(const label of ['关闭建筑管理','关闭中枢商店'])assert.ok(game.includes(label),`沉浸工作区缺少明确退出文案：${label}`);
assert.doesNotMatch(game,/workspaceExit\('关闭技能矩阵'|workspaceExit\('关闭职业档案'/,'技能与职业成为一级页后不得残留沉浸工作区关闭栏');
assert.doesNotMatch(game,/关闭建筑操作|退出界面/,'退出按钮不得使用不知道会关闭什么的抽象文案');
assert.equal((html.match(/<button data-tab="/g)||[]).length,5,'底部主导航必须固定为五个等宽入口');
for(const tab of ['char','career','skill','bag','task'])assert.match(html,new RegExp(`data-tab="${tab}"`),`底部主导航缺少 ${tab} 入口`);
for(const icon of ['icon-career','icon-skill'])assert.match(html,new RegExp(`symbol id="${icon}"`),`新增一级导航必须使用统一 SVG 图标：${icon}`);
for(const id of ['pierce','heavy','pulse-burst','combat-rhythm','kinetic-brace','reactive-armor','phase-strike','weakpoint-model','salvage-sense','field-sorting','precision-fab','thermal-control','bio-cycle','adaptive-culture','quick-scavenge','pulse-mining','precision-dismantle','strata-excavation','field-repair','spore-boost','sterile-sampling','tactical-scan','shield-bash','heavy-blow'])assert.match(html,new RegExp(`symbol id="icon-skill-${id}"`),`技能必须拥有独立 SVG 图标：${id}`);
for(const id of ['vanguard','bulwark','infiltrator','salvager','fabricator','biologist'])assert.match(html,new RegExp(`symbol id="icon-career-${id}"`),`职业必须拥有独立 SVG 纹章：${id}`);
for(const role of ['vanguard','bulwark','infiltrator'])for(const sex of ['male','female'])assert.equal(fs.existsSync(path.join(root,'assets','career-portraits-v1',`${role}-${sex}.png`)),true,`主战职业缺少 ${role}-${sex} 立绘`);
assert.match(game,/function activeCareerPortraitSrc\(\)[\s\S]*careerRecord\('main'\)[\s\S]*careerPortraitSrc/,'背包人物立绘必须只跟随当前主战职业');
assert.match(game,/function lifeCareerModuleMarkup\(compact\)[\s\S]*careerRecords\('life'\)[\s\S]*life-module-rack/,'多个副职业必须以可并存模块挂载，不能替换人物立绘');
assert.match(game,/function appendCombatEffects\(screen\)[\s\S]*battle-effect-layer[\s\S]*queueCombatFx\('player','skill',k\)/,'战斗攻击和技能必须进入瞬时动效层');
assert.match(system,/Actions are short lived combat events[\s\S]*\.battle-effect-layer[\s\S]*@keyframes battle-fx-impact/,'战斗动效必须由统一视觉系统提供');
assert.match(game,/function primaryTabKey\(\)[\s\S]*charView==='careers'[\s\S]*charView==='skills'/,'职业与技能一级入口必须映射到正确的底栏选中态');
assert.match(game,/rootPage=\['camp','explore','character','skills','careers','bag','tasks','settings'\][\s\S]*immersiveWorkspace=\['facility','construction','settlement-shop','npc'\]/,'职业技能必须归入主导航页而不是沉浸工作区');
assert.match(game,/function skillPageEntries\(view\)[\s\S]*Object\.keys\(MASTERIES\)\.map[\s\S]*Object\.keys\(SKILLS\)\.filter/,'技能能力库必须保留锁定能力并展示解锁路径');
assert.match(game,/function renderCareerPanel\(box\)[\s\S]*\['current','main','life'\][\s\S]*career-view-tabs/,'职业页必须把当前配置、战斗路线和生活路线分层');
assert.match(system,/Primary progression pages[\s\S]*\.skill-library-card\.locked[\s\S]*\.career-path-card\.current/,'技能与职业一级页必须从统一视觉系统获得状态样式');
assert.match(system,/RPG progression codex[\s\S]*\.tone-active[\s\S]*\.tone-field[\s\S]*\.career-primary-stage[\s\S]*\.career-life-dossiers/,'技能与职业必须使用统一 RPG 战典皮肤、语义色和主副职业层级');
assert.match(game,/function renderSkillBrowser\(view,onMutate\)[\s\S]*replaceMountedNode\(detailHost\.children\[0\][\s\S]*function refreshSkillPanel\(\)[^\n]*_refreshSkillPanel/,'技能选择必须只替换详情，外部刷新必须委托已挂载的局部控制器');
assert.match(game,/function switchView\(id\)[\s\S]*replaceMountedNode\(content,fresh,box\)[\s\S]*function refreshCareerPanel\(\)[^\n]*_refreshCareerPanel/,'职业分段必须只替换内容区，外部刷新必须委托已挂载的局部控制器');
assert.doesNotMatch(game,/function refresh(?:Skill|Career)Panel\(\)[^\n]*replaceChildren/,'技能与职业刷新入口不得清空并重建整个页面');
assert.match(rules,/角色 \/ 职业 \/ 技能 \/ 背包 \/ 任务[\s\S]*常驻战斗技能栏 → 战斗 \/ 生活 \/ 精通分类 → 已学能力 → 单份详情[\s\S]*当前配置 \/ 战斗路线 \/ 生活路线/,'统一规范必须固定五项主导航、默认已学与单份详情');
assert.match(rules,/主战职业是唯一人物身份[\s\S]*男女两张同构全身立绘[\s\S]*副职业不是人物身份[\s\S]*可并存的资质徽章/,'统一规范必须固定主战立绘与多副职模块的边界');
assert.match(rules,/每个技能 ID 必须拥有自己的[\s\S]*战斗按钮与释放动效复用同一个符号[\s\S]*普通攻击、敌方攻击和每种主动技能/,'统一规范必须固定技能图标与战斗反馈');
assert.doesNotMatch(game,/<span class="cc-icon">(?:DNA|JOB|SKL)<\/span>/,'角色入口必须使用统一 SVG sprite，不能使用文字缩写冒充图标');
assert.match(game,/function uiModuleHeader\(/,'页面标题必须通过统一模块头构造器创建');
for(const cls of ['construction-head','market-head','task-head','settings-head'])assert.match(game,new RegExp(`uiModuleHeader\\([^\n]+${cls}`),`${cls} 必须复用统一模块头而不是自建皮肤`);
assert.match(game,/facility-nav facility-module-head ui-module-header[\s\S]*facility-header-art ui-module-header__mark ui-art-frame/,'设施操作页必须复用统一模块头和建筑插画框');
assert.match(game,/function facilityHeaderDetail\(b\)[\s\S]*b\.kind==='defense'[\s\S]*campDefenseStats\(\)[\s\S]*b\.kind==='garden'[\s\S]*gardenSlotCount\(\)[\s\S]*b\.kind==='rest'/,'哨戒塔、菌圃与休眠仓的关键状态必须集中进顶部设施面板');
assert.doesNotMatch(game,/function facilityHeader\(box,b\)[\s\S]{0,800}facility-hero/,'设施标题下方不得再次生成重复名称面板');
assert.match(system,/\.recipe-station-top \.facility-module-head \.facility-header-summary \{ display:flex; \}/,'分栏设施页不得用旧规则隐藏顶部属性总览');
assert.match(system,/Beacon, recovery and mastery extensions[\s\S]*\.beacon-inline-picker[\s\S]*\.mastery-book-choice\.selected/,'信标、回收与精通手册必须由统一视觉系统提供材质和状态');
assert.match(system,/Beacon, recovery and mastery extensions[\s\S]*\.beacon-console[\s\S]*\.beacon-rings \{[^}]*var\(--ui-anomaly\)[^}]*var\(--ui-surface-sunken\)/,'信标主体也必须使用统一材质和异常色令牌，不能只统一选层控件');
assert.match(system,/\.garden-bed-main b \{[^}]*var\(--ui-type-secondary\)[^}]*\}[\s\S]*\.garden-bed-main small \{[^}]*var\(--ui-type-secondary\)[\s\S]*\.garden-bed-skill small \{[^}]*var\(--ui-type-code\)/,'菌圃可读文字不得退回 6–8px 私有字号');
assert.doesNotMatch(layout,/\.beacon-inline-picker\{[^}]*(?:color|background|border|box-shadow):|\.mastery-book-batch\{[^}]*(?:color|background|border|box-shadow):/,'新设施组件不得在旧布局文件中维护私有视觉皮肤');
for(const id of ['nutrient','blackwood','protein','glow','biosample','crystal'])assert.match(html,new RegExp(`symbol id="icon-garden-${id}"`),`菌圃缺少统一 SVG 培养图标：${id}`);
assert.match(game,/maxQty:state\.inv\[id\]/,'装备拆解必须把实际闲置数量传给统一批量控件');
assert.match(game,/heldId=Object\.keys\(r\.cost\)\[0\][\s\S]{0,220}heldId/,'材料回收卡必须展示待处理库存，不能把产出库存当成可拆数量');
assert.match(game,/\[1,10,100\]\.forEach[\s\S]{0,240}setCount\(count\+delta\)/,'精通手册必须提供就地更新的 +100 批量按钮');
assert.doesNotMatch(game,/kind==='masteryBook'[\s\S]{0,2200}setCount[^;]+render\(\)/,'调整精通手册数量不得重建整页造成闪烁');
assert.match(game,/function closeSiteSheet\(\)[\s\S]{0,180}site-sheet-backdrop[\s\S]{0,100}save\(\)/,'上下文弹层关闭时必须直接移除弹层，不得重建来源页');
for(const localRefresh of ['refreshBagPanel','refreshTechSelection','refreshGeneSelection','refreshTaskPanel','refreshNpcMode','refreshSkillPanel','refreshCareerPanel'])assert.match(game,new RegExp('function '+localRefresh+'\\('),localRefresh+' 必须提供局部刷新入口');
assert.match(rules,/再次点击当前选项必须无操作[\s\S]*禁止调用全局 `render\(\)`[\s\S]*背包候选列表、人物容器和滚动区须保持原节点/,'统一规范必须要求原节点局部更新，不能用恢复滚动掩盖整体重建');
assert.match(system,/\.rpg-equipment-detail[\s\S]*\.battle-role-meter/,'装备对比与职业充能皮肤必须在统一样式文件内');
assert.doesNotMatch(html,/rpg-panels-v1\.css/,'不得另挂成长面板私有皮肤');
assert.match(game,/task-focus ui-panel[\s\S]*task-focus-details ui-disclosure/,'任务总览必须突出一个目标，次要说明使用统一展开组件');
assert.match(game,/PRIMARY OBJECTIVE[\s\S]*NEXT ACTION \/\/ 下一步[\s\S]*完成回报/,'任务首页必须先集中展示首要目标、下一步和回报');
assert.match(game,/taskBoardTab\('active','进行中'[\s\S]*taskBoardTab\('main','主线'[\s\S]*taskBoardTab\('archive','档案'/,'任务面板必须用短中文标签区分当前行动、主线与只读档案');
assert.match(layout,/#panel\.tasks-console[\s\S]*\.task-focus[\s\S]*\.task-queue-card[\s\S]*\.task-record-grid/,'任务面板必须拥有首要任务、待办队列与档案的集中布局');
assert.match(system,/\.task-board-nav[\s\S]*\.task-focus[\s\S]*\.task-queue-card[\s\S]*\.task-main-row[\s\S]*\.task-record-card/,'任务指挥台的状态与材质必须由统一视觉系统收口');
assert.match(system,/Material skin convergence[\s\S]*\.task-overview[\s\S]*\.build-card/,'旧页面的实际皮肤必须在统一样式文件中收口');
assert.match(system,/#panel \.facility-upgrade-trigger[\s\S]*\.facility-upgrade-sheet/,'设施升级入口和详情必须由统一样式文件收口');
assert.match(system,/Cinematic battle interface[\s\S]*\.battle-target-hud[\s\S]*\.battle-range-ring[\s\S]*\.battle-command-dock/,'目标锁定、战术准星与指令坞必须由统一样式文件收口');
assert.match(rules,/四层材料关系/,'设计规范必须明确开屏、人物和物品共同使用的材质层级');
assert.match(rules,/怪物立绘与战斗背景[\s\S]*object-fit: contain[\s\S]*禁止通过裁掉或大面积盖住怪物解决/,'设计规范必须明确怪物全身铺满战斗背景且禁止裁切或遮挡');
assert.match(rules,/不能继续向 `style\.css` 增加 `color \/ background \/ border \/ shadow`/,'规范必须阻止业务页面继续创建私有皮肤');
assert.match(rules,/选择精通 → 调整数量 → 确认研读[\s\S]*Lv101 起解锁[\s\S]*进入实际数值公式/,'统一规范必须固定精通手册流程与100级后超限成长规则');
assert.match(html,/style\.css\?v=[^"\s]*workspace3/,'页面布局变更必须刷新浏览器缓存参数');
assert.match(html,/ui-system\.css\?v=[^"\s]*workspace3/,'统一样式变更必须刷新浏览器缓存参数');
assert.match(html,/ui-system\.css\?v=[^"\s]*longcopy1/,'长数值与详情抗溢出变更必须刷新统一样式缓存参数');
assert.match(html,/game\.js\?v=[^"\s]*adaptivehud1/,'自适应状态结构变更必须刷新 game.js 缓存参数');
assert.match(html,/game\.js\?v=[^"\s]*workspace3/,'页面骨架变更必须刷新浏览器缓存参数');
assert.match(html,/game\.js\?v=[^"\s]*interactionfix1/,'局部交互刷新变更必须刷新 game.js 缓存参数');
for(const asset of ['style.css','ui-system.css','game.js'])assert.match(html,new RegExp(asset.replace('.',String.raw`\.`)+String.raw`\?v=[^"\s]*taskboard1`),`任务面板变更必须刷新 ${asset} 缓存参数`);
for(const asset of ['style.css','ui-system.css','game.js'])assert.match(html,new RegExp(asset.replace('.',String.raw`\.`)+String.raw`\?v=[^"\s]*progressiontabs1`),`技能职业一级页变更必须刷新 ${asset} 缓存参数`);
for(const asset of ['style.css','ui-system.css','game.js'])assert.match(html,new RegExp(asset.replace('.',String.raw`\.`)+String.raw`\?v=[^"\s]*gamefx1`),`职业立绘、技能图标与战斗动效变更必须刷新 ${asset} 缓存参数`);
for(const asset of ['style.css','ui-system.css','game.js'])assert.match(html,new RegExp(asset.replace('.',String.raw`\.`)+String.raw`\?v=[^"\s]*loadoutfx1`),`人物装备融合层变更必须刷新 ${asset} 缓存参数`);
for(const asset of ['style.css','ui-system.css','game.js'])assert.match(html,new RegExp(asset.replace('.',String.raw`\.`)+String.raw`\?v=[^"\s]*stationfix2`),`建筑配方切换、培养块技能与菌圃图标变更必须刷新 ${asset} 缓存参数`);
assert.match(game,/function buildRecipeWorkbenchDetail[\s\S]*const selectEntry=entry=>[\s\S]*buildRecipeWorkbenchDetail\(entry,ui,opts,refresh,tone\)/,'配方切换必须只重建受控详情区，不能重建上方选择器');
assert.doesNotMatch(game,/function renderRecipeWorkbench[\s\S]{0,5000}shell\.replaceWith/,'建筑配方工作台不得继续依赖 replaceWith 更新选择结果');
assert.match(system,/\.garden-bed-skill[\s\S]*\.garden-bed-skill\.active/,'每个培养块上的培育师技能必须由统一视觉系统提供可用与禁用状态');
assert.match(rules,/男女固定姿势母版[\s\S]*独立男女穿戴层[\s\S]*不能用库存图标或半透明投影冒充穿鞋、穿甲[\s\S]*未通过验收的资源不得接入正式人物/,'统一规范必须区分真正的逐部位穿戴与库存图标叠加');

console.log('ui-system.test.js: all assertions passed');
assert.match(html,/<script src="wardrobe\.js\?v=[^"]+"><\/script>[\s\S]*<script src="game\.js/,"穿戴映射必须在游戏初始化前加载");
assert.match(game,/function refreshDollArt[\s\S]*updateWearablePortrait\(rig,state.playerAppearance,P\(\)\.equip,careerRecord\('main'\)\?\.id,careerRecords\('life'\)\)/,"正式背包必须传入性别、主职和并存副职业");
assert.doesNotMatch(game,/function equipmentPortraitLayers|class="doll-gear-piece/,"正式背包不得保留库存图标拼贴实现");
assert.match(system,/\.doll-art-host \.doll-wearable\{[^}]*max-width:66%/,"装配母版必须使用统一响应式宽度");
